version: '3.8'
services:
  sellaf-api-prod:
    image: 022024849961.dkr.ecr.us-east-2.amazonaws.com/sellaf-api:${IMAGE_VERSION}
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4005:4005
    depends_on:
      - prod-db
      - redis
      - keycloak-server
    platform: "linux/amd64"
  db-server:
    image: postgres:13-alpine
    ports:
      - "5434:5432"
    env_file:
      - ./.env.db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  keycloak-server:
    image: auth-server
    build:
      context: .
      dockerfile: Dockerfile.kc
    env_file:
      - ./.env.kc
    ports:
      - "8082:8888"
    depends_on:
      - prod-db
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis:/data
volumes:
  postgres_data:
  redis:
