version: '3.8'
services:
  sellaf-api:
    container_name: 'sellaf-v2-api'
    image: 'sellaf-v2-api-image'
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    env_file:
      - ./.env
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - 4005:4005
    depends_on:
      - dev-db
  dev-db:
    image: postgres:13-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: rouche
      POSTGRES_PASSWORD: rouche
      POSTGRES_DB: sellaf-dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  adminer:
    image: adminer
    depends_on:
      - dev-db
    restart: always
    ports:
      - 8080:8080
  keycloak-server:
    image: quay.io/keycloak/keycloak:19.0.2
    ports:
      - 8082:8080
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: sellaf-dev
      DB_USER: rouche
      DB_SCHEMA: public
      DB_PASSWORD: rouche
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    depends_on:
      - dev-db
    command: "start-dev --http-relative-path /auth"
volumes:
  postgres_data:
