FROM node:18-alpine As development

USER root
WORKDIR /usr/src/app
COPY package*.json ./
COPY prisma ./prisma/

# Installing prerequisites for bcrypt, then install node_modules,
# compile bcrypt and delete prerequisites for smaller docker image
RUN apk add --no-cache make gcc g++ python3 && \
  npm ci && \
  npm rebuild bcrypt --build-from-source && \
  apk del make gcc g++ python3

RUN apk add --no-cache postgresql-client

COPY . .
COPY ./wait-for-pg-and-exec.sh /wait-for-pg-and-exec.sh
RUN chmod +x /wait-for-pg-and-exec.sh

# Build for production
FROM development As builder

RUN npm run build
ENV APP_ENVIRONMENT production

RUN npm ci --only=production && npm cache clean --force

# For production
FROM node:18-alpine As production

COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY --from=builder /usr/src/app/dist ./dist

EXPOSE 4005

CMD [ "node", "dist/main.js" ]