version: '3.8'
services:
  sellaf-api:
    container_name: 'sellaf-v2-api'
    image: 'sellaf-v2-api-image'
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4005:4005
    depends_on:
      - dev-db
      - redis
    platform: "linux/amd64"
    command: npm run start:dev
  dev-db:
    image: postgres:13-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: rouche
      POSTGRES_PASSWORD: rouche
      POSTGRES_DB: sellaf-dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  adminer:
    image: adminer
    depends_on:
      - dev-db
    restart: always
    ports:
      - 8080:8080
  keycloak-server:
    image: quay.io/keycloak/keycloak:19.0.2
    ports:
      - "8082:8080"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: sellaf-dev
      DB_USER: rouche
      DB_SCHEMA: public
      DB_PASSWORD: rouche
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    depends_on:
      - dev-db
    command: start-dev
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis:/data
volumes:
  postgres_data:
  redis:
