FROM quay.io/keycloak/keycloak:19.0.2

USER root
RUN microdnf update -y && microdnf install -y jq && microdnf clean all

COPY ./keycloak-scripts /startup-scripts

RUN find /startup-scripts -type f -exec chmod 755 {} \;

ENTRYPOINT [ "/startup-scripts/kc-entrypoint.sh", "start-dev" ]
