export const SEND_EMAIL_QUEUE = 'SEND_EMAIL';
export const RENEW_SUBSCRIPTION_QUEUE = 'RENEW_SUBSCRIPTION';
export const TERMINATE_SUBSCRIPTION_QUEUE = 'TERMINATE_SUBSCRIPTION_QUEUE';

export const QUEUES = {
  SEND_EMAIL_QUEUE,
  RENEW_SUBSCRIPTION_QUEUE,
  TERMINATE_SUBSCRIPTION_QUEUE,
} as const;
