import { registerAs } from '@nestjs/config';

export const applicationConfig = registerAs('application', () => ({
  databaseUrl: process.env.DATABASE_URL,
  port: process.env.PORT,
  appEnvironment: process.env.APP_ENVIRONMENT,
  keycloakServer: process.env.KEYCLOAK_SERVER,
  keycloakServerRealmName: process.env.KEYCLOAK_SERVER_REALM_NAME,
  keycloakAdminClientId: process.env.KEYCLOAK_ADMIN_CLIENT_ID,
  keycloakAdminClientSecret: process.env.KEYCLOAK_ADMIN_CLIENT_SECRET,
  smtpHost: process.env.SMTP_HOST,
  smtpUsername: process.env.SMTP_USERNAME,
  smtpPassword: process.env.SMTP_PASSWORD,
  redisHost: process.env.REDIS_HOST,
  redisPort: process.env.REDIS_PORT,
  bcryptTokenSalt: process.env.BCRYPT_TOKEN_SALT,
  kcSellafApiClientId: process.env.KC_SELLAF_API_CLIENT_ID,
  kcSellafApiClientSecret: process.env.KC_SELLAF_API_CLIENT_SECRET,
  adminUsername: process.env.ADMIN_USERNAME,
  adminEmail: process.env.ADMIN_EMAIL,
  adminPassword: process.env.ADMIN_PASSWORD,
  flutterwave: {
    apiBaseUrl: process.env.FLUTTERWAVE_API_BASE_URL,
    livePublicKey: process.env.FLUTTERWAVE_PUBLIC_KEY,
    liveSecretKey: process.env.FLUTTERWAVE_SECRET_KEY,
    liveEncryptionKey: process.env.FLUTTERWAVE_ENCRYPTION_KEY,
    testPublicKey: process.env.FLUTTERWAVE_TEST_PUBLIC_KEY,
    testSecretKey: process.env.FLUTTERWAVE_TEST_SECRET_KEY,
    testEncryptionKey: process.env.FLUTTERWAVE_TEST_ENCRYPTION_KEY,
  },
  coinbase: {
    apiBaseUrl: process.env.COINBASE_API_BASE_URL,
    apiKey: process.env.COINBASE_API_KEY,
  },
  frontendUrl: process.env.FRONTEND_URL,
  fiatPaymentGateway: process.env.FIAT_PAYMENT_GATEWAY,
}));
