export const USER_GROUPS = {
  AFFILIATE_USER_GROUP: 'AFFILIATE_USER_GROUP',
  STORE_OWNER_GROUP: 'STORE_OWNER_GROUP',
  SUPER_ADMIN_USER_GROUP: 'SUPER_ADMIN_USER_GROUP',
} as const;

export type UserGroups = typeof USER_GROUPS[keyof typeof USER_GROUPS];
